export const CONFIG = {
    defaultTime: 60,
    timeOptions: [15, 60],
    symbols: [
        { value: 'I', label: 'I (Rome)' },
        { value: 'II', label: 'II (Rome)' },
        { value: 'III', label: 'III (Rome)' },
        { value: 'V', label: 'V (Rome)' },
        { value: 'X', label: 'X (Rome)' },
        { value: '100', label: '100 (Rome)' },
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: 'A', label: 'A' },
        { value: 'B', label: 'B' },
        { value: 'C', label: 'C' },
        { value: 'D', label: 'D' },
        { value: 'E', label: 'E' },
        { value: 'F', label: 'F' },
        { value: '↑', label: '↑' },
        { value: '↓', label: '↓' },
        { value: '←', label: '←' },
        { value: '→', label: '→' },
        { value: '↕', label: '↕' },
        { value: '↔', label: '↔' },
        { value: '□', label: '□' },
        { value: '○', label: '○' },
        { value: '△', label: '△' },
        { value: '∠', label: '∠ (Left)' },
        { value: '∠R', label: '∠ (Right)' },
        { value: '▭', label: '▭ (Parallel right)' },
        { value: '▯', label: '▯ (Parallel left)' }
    ]
}; 